[versions]
kotlin     = "2.2.0"
agp        = "8.0.2"
hilt       = "2.56.2"
coroutines = "1.8.1"
room = "2.7.2"
supabase = "3.2.0"


[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android",    version.ref = "kotlin" }
kotlin-kapt    = { id = "org.jetbrains.kotlin.kapt",       version.ref = "kotlin" }
android-app    = { id = "com.android.application",        version.ref = "agp" }
hilt-android   = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
room-runtime    = { module = "androidx.room:room-runtime",     version.ref = "room" }
room-ktx        = { module = "androidx.room:room-ktx",         version.ref = "room" }
room-compiler   = { module = "androidx.room:room-compiler",    version.ref = "room" }
hilt-android    = { module = "com.google.dagger:hilt-android",version.ref = "hilt" }
hilt-compiler   = { module = "com.google.dagger:hilt-compiler",version.ref = "hilt" }

supabase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version = "3.2.0" }

